manifest:
  defaults:
    revision: main
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: mikel247 # Replace with your GitHub username
      url-base: https://github.com/mikel247/zmk-behavior-random
  projects:
    - name: zmk
      remote: zmkfirmware
      import: app/west.yml
    - name: zmk-behavior-random # This must match your module repo name
      remote: your-username
      revision: main
  self:
    path: config
